version: '1.0'
services:
  jupyter-lab:
    build: .
    ports:
     - "8888:8888"
    volumes:
      - ../Miniproject:/app  
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]